title:             Max and Yuki
email:             leizhao.mail@qq.com
description:       An ordinary blog of a programmer
author:            Lei Zhao
baseurl:           "/"
url:               "http://maxandyuki.github.io"

# Social Profiles
twitter_username:  #
github_username:   MaxandYuki
facebook_username: #

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
